import { Injectable } from '@angular/core';
import { Subject } from 'rxjs';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Task } from './task.model';

@Injectable({ providedIn: 'root' })
export class TaskService {
  tasks: Task[] = [];
  taskListChangedEvent = new Subject<Task[]>();
  taskSelectedEvent = new Subject<Task | null>();

  private baseUrl = 'http://localhost:3000/tasks';

  constructor(private http: HttpClient) {}

  // GET all tasks
  getTasks() {
    this.http.get<{ message: string; tasks: Task[] }>(this.baseUrl)
      .subscribe(response => {
        this.tasks = response.tasks;
        this.taskListChangedEvent.next(this.tasks.slice());
      }, error => {
        console.error('Error fetching tasks:', error);
      });
  }

  // GET a single task by id
  getTask(id: string): Task | null {
    return this.tasks.find(t => t.id === id) || null;
  }

  // ADD a new task
  addTask(newTask: Task) {
    if (!newTask) return;

    newTask.id = ''; // ID is generated by the backend
    const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

    this.http.post<{ message: string; task: Task }>(this.baseUrl, newTask, { headers })
      .subscribe(response => {
        this.tasks.push(response.task);
        this.taskListChangedEvent.next(this.tasks.slice());
      }, error => {
        console.error('Error adding task:', error);
      });
  }

  // UPDATE an existing task
  updateTask(originalTask: Task, newTask: Task) {
    if (!originalTask || !newTask) return;

    const pos = this.tasks.findIndex(t => t.id === originalTask.id);
    if (pos < 0) return;

    newTask.id = originalTask.id;
    const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

    this.http.put(this.baseUrl + '/' + originalTask.id, newTask, { headers })
      .subscribe(() => {
        this.tasks[pos] = newTask;
        this.taskListChangedEvent.next(this.tasks.slice());
      }, error => {
        console.error('Error updating task:', error);
      });
  }

  // DELETE a task
  deleteTask(task: Task | null) {
    if (!task) return;

    const pos = this.tasks.findIndex(t => t.id === task.id);
    if (pos < 0) return;

    this.http.delete(this.baseUrl + '/' + task.id)
      .subscribe(() => {
        this.tasks.splice(pos, 1);
        this.taskListChangedEvent.next(this.tasks.slice());
      }, error => {
        console.error('Error deleting task:', error);
      });
  }
}
