import { Injectable } from '@angular/core';
import { Subject } from 'rxjs';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Task } from './task.model';

@Injectable({ providedIn: 'root' })
export class TaskService {
  tasks: Task[] = [];
  taskListChangedEvent = new Subject<Task[]>();
  taskSelectedEvent = new Subject<Task | null>();

  private baseUrl = 'http://localhost:3000/tasks';

  constructor(private http: HttpClient) {}

  // GET all tasks
  getTasks() {
    this.http.get<{ message: string; tasks: Task[] }>(this.baseUrl)
      .subscribe({
        next: (response) => {
          this.tasks = response.tasks;
          this.taskListChangedEvent.next(this.tasks.slice());
        },
        error: (error) => {
          console.error('Error fetching tasks:', error);
        }
      });
  }

  // GET a single task by _id
  getTask(_id: string): Task | null {
    return this.tasks.find(t => t._id === _id) || null;
  }

  // ADD a new task
  addTask(newTask: Task) {
    if (!newTask) return;

    // _id is generated by backend, id can remain empty for local use
    newTask.id = '';

    const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

    this.http.post<{ message: string; task: Task }>(this.baseUrl, newTask, { headers })
      .subscribe({
        next: (response) => {
          this.tasks.push(response.task);
          this.taskListChangedEvent.next(this.tasks.slice());
        },
        error: (error) => {
          console.error('Error adding task:', error);
        }
      });
  }

  // UPDATE an existing task
  updateTask(originalTask: Task, newTask: Task) {
    if (!originalTask || !newTask || !originalTask._id) return;

    const pos = this.tasks.findIndex(t => t._id === originalTask._id);
    if (pos < 0) return;

    newTask._id = originalTask._id;
    const headers = new HttpHeaders({ 'Content-Type': 'application/json' });

    this.http.put(`${this.baseUrl}/${originalTask._id}`, newTask, { headers })
      .subscribe({
        next: () => {
          this.tasks[pos] = newTask;
          this.taskListChangedEvent.next(this.tasks.slice());
        },
        error: (error) => {
          console.error('Error updating task:', error);
        }
      });
  }

  // DELETE a task
  deleteTask(task: Task | null) {
    if (!task || !task._id) {
      console.error('Task ID missing', task);
      return;
    }

    const pos = this.tasks.findIndex(t => t._id === task._id);
    if (pos < 0) return;

    this.http.delete(`${this.baseUrl}/${task._id}`)
      .subscribe({
        next: () => {
          this.tasks.splice(pos, 1);
          this.taskListChangedEvent.next(this.tasks.slice());
        },
        error: (error) => {
          console.error('Error deleting task:', error);
        }
      });
  }
}
